name: Deploy to Deno

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build client
        run: npm run build:client

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_TOKEN }}
        run: |
          deno run -A https://deno.land/x/deploy/deployctl.ts deploy \
            --project=${{ secrets.DENO_PROJECT }} \
            --prod \
            deno_main.ts

