name: Build UI and publish static branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build client (Vite)
        run: npm run build:client

      - name: Prepare publish directory
        run: |
          rm -rf publish
          mkdir -p publish
          cp -r dist/public/* publish/
          # prevent Jekyll processing if viewed on GitHub Pages
          touch publish/.nojekyll

      - name: Publish to static-dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish
          publish_branch: static-dist
          force_orphan: true

